version: '3.8'
services:
  nuxt-app:
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    #environment:
    #  - HOST=0.0.0.0
    command: npm run dev 